package com.university.Library_Management_System.Enum;

public enum Genre {
    ActionAdventureFiction,
    ChildrensFiction,
    ClassicFiction,
    ContemporaryFiction,
    Fantasy,
    GraphicNovel,
    HistoricalFiction,
    Horror,
    LGBTQ,
    LiteraryFiction,
    Mystery,
    NewAdult,
    Romance,
    Satire,
    ScienceFiction,
    ShortStory ,
    Thriller,
    Western,
    WomenFiction,
    YoungAdult,
    ArtPhotography,
    AutobiographyMemoir,
    Biography,
    Essays,
    FoodDrink,
    History,
    HowToGuides,
    HumanitiesSocialSciences,
    Humor,
    Parenting,
    Philosophy,
    ReligionSpirituality,
    ScienceTechnology ,
    SelfHelp,
    Travel,
    TrueCrime,
    ADVENTURE
}
